### ISSUE TITLE
erb_lint support? 

### ISSUE THREAD

**Issue by alxjrvs** [AdWerx/pronto-ruby#132]
Thanks for the great workflow! I was looking to add `erb_lint` support, when I noticed that the `pronto-erb_lint` gem is already required in the Gemfile, and the changelog suggested that it was already supported a number of years ago. 

I added `erb_lint` to the end of my config: 
```yml
name: Pronto
on: [ pull_request ]
jobs:
  pronto:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      statuses: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: HeRoMo/pronto-action@v1.35.0
        with:
          github_token: ${{ secrets.GNARBOT_TOKEN }}
          runner: rubocop brakeman rails_best_practices erb_lint
          formatters: text github_status github_pr_review
```

When I run it, I get this error:
<img width="1027" alt="Screen Shot 2022-07-26 at 8 32 04 PM" src="https://user-images.githubusercontent.com/174825/181135142-c00f14be-d4a7-40cd-8089-472c1621b692.png">

Strictly speaking, `erb_lint` isn't in the list of supported runners. However, it looks like it should work according to the Dockerfile.  Is there any particular reason erb_lint isn't supported?
