### ISSUE TITLE
failed to parse revision specifier - Invalid pattern ''

### ISSUE THREAD

**Issue by mbajur** [AdWerx/pronto-ruby#203]
I have a following action config:

```
name: Pronto

on:
  - pull_request

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    steps:
    - uses: actions/checkout@v1
    - run: echo `git merge-base --fork-point dev`
    - run: echo `git merge-base --fork-point origin/dev`
    - run: echo `git merge-base --fork-point origin/master`
    - id: get_base
      run: echo ::set-output name=sha::`git merge-base HEAD origin/dev || git merge-base HEAD origin/master`

    - name: Run Pronto
      uses: adwerx/pronto-ruby@v2.4
      with:
        target: ${{ steps.get_base.outputs.sha }}
        runners: >-
          rails_schema rails_data_schema
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

and it raises a following error:

```
/usr/local/bundle/gems/pronto-0.10.0/lib/pronto/git/repository.rb:87:in `merge_base': failed to parse revision specifier - Invalid pattern '' (Rugged::InvalidError)
	from /usr/local/bundle/gems/pronto-0.10.0/lib/pronto/git/repository.rb:87:in `merge_base'
	from /usr/local/bundle/gems/pronto-0.10.0/lib/pronto/git/repository.rb:17:in `diff'
	from /usr/local/bundle/gems/pronto-0.10.0/lib/pronto.rb:62:in `run'
	from /usr/local/bundle/gems/pronto-0.10.0/lib/pronto/cli.rb:66:in `block in run'
	from /usr/local/bundle/gems/pronto-0.10.0/lib/pronto/cli.rb:64:in `chdir'
	from /usr/local/bundle/gems/pronto-0.10.0/lib/pronto/cli.rb:64:in `run'
	from /usr/local/bundle/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-0.20.3/lib/thor/invocation.rb:[12](https://github.com/Cuseum/spotzer-cms/actions/runs/6392060242/job/17348571308?pr=2948#step:9:13)6:in `invoke_command'
	from /usr/local/bundle/gems/thor-0.[20](https://github.com/Cuseum/spotzer-cms/actions/runs/6392060242/job/17348571308?pr=2948#step:9:21).3/lib/thor.rb:387:in `dispatch'
	from /usr/local/bundle/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /runner/pronto:41:in `block in <main>'
	from /runner/pronto:40:in `chdir'
	from /runner/pronto:40:in `<main>'
```

Any idea what can be done about it?
