### ISSUE TITLE
.pronto-bundler_audit.yml not loading

### ISSUE THREAD

**Issue by mbajur** [AdWerx/pronto-ruby#5]
Hey there!

I'm trying to add one vulnerability to ignored list using `.pronto-bundler_audit.yml` config file recommended by `pronto-bundler_audit` authors, it's contents looks as follows:

```
Advisories:
  Ignore:
    - CVE-2015-9284
```

While running pronto locally using `pronto run --runner bundler_audit` ignores this vulnerability perfectly fine, github action seems to not be loading this file and raises a check fail for given vulnerability.

Any idea what's going on in here? If you want to reproduce that, just run this action on ruby repo with `gem 'omniauth', '1.9.0'` entry in Gemfile and the config file pasted above.

Thanks!

**Comment by jbielick** [comment]
What version of pronto-ruby are you using? Could you share a snippet of your action yaml?

**Comment by mbajur** [comment]
Here is my action:

```
name: Pronto

on:
  - push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - id: get_base
      run: echo ::set-output name=sha::`git merge-base HEAD origin/dev || git merge-base HEAD origin/master`

    - name: Run Pronto
      uses: adwerx/pronto-ruby@v1.1.0
      with:
        target: ${{ steps.get_base.outputs.sha }}
        runners: >-
          rubocop bundler_audit rails_schema brakeman
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Updating it to 1.1.2 or master gives me:

```
Current runner version: '2.162.0'
Prepare workflow directory
Prepare all required actions
Download action repository 'actions/checkout@v1'
Download action repository 'adwerx/pronto-ruby@v1.1.1'
##[error]'Dockerfile.action' should be either '[path]/Dockerfile' or 'docker://image[:tag]'.
```
