### ISSUE TITLE
Fails at rubocop-performance

### ISSUE THREAD

**Issue by maria-kravtsova** [AdWerx/pronto-ruby#6]
Wow, love this, and would love to use it, unfortunately when trying to set it up on private repo with the suggested setup I was getting this error: 

```
/usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- rubocop-performance (LoadError)
```

Was wondering if you had some suggestions.

**Comment by jbielick** [comment]
🤔 Would you mind pasting your rubocop config here? The performance cops are an [additional gem](https://github.com/rubocop-hq/rubocop-performance) that probably isn't installed in this docker image at the moment. 

Might be an easy fix, but the config would also help as I don't have or use one with performance cops enabled.

**Comment by maria-kravtsova** [comment]
Oh, I see, my `rubocop.yml` is

```
require: 
  - rubocop-performance
  - rubocop-rails

Metrics/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
```
